### ISSUE TITLE
When resizing the panel some icons resize, others don't.

### ISSUE THREAD

**Issue by bareego** [linuxmint/xfce4-xapp-status-plugin#10]
This is obviously affecting the XFCE4 version of Mint.

I've moved the xfce4-panel to the bottom and resized it to 60 pixels.
The icons on the left in the Status Tray can be resized through their property panel (fix done in beta).
But some of the Icons on the right will not resize up, namely the Network Icon and the Update Manager.

This has only changed since Mint 22. Have had this on 2 machines, one running the 22 beta and then the current 22 release version.
Another machine upgraded from 21.3 to 22 showed the same issue.

I've checked the package info for xfce4-panel and it said it's moved from the debian to ubuntu people to maintain it.
Running "ubuntu-bug xfce4-panel" says: "The problem cannot be reported: This does not seem to be an official Linux package."
So I assume it's a Mint bug and report it here.
![tray](https://github.com/user-attachments/assets/170a830a-06f0-45ce-a85a-52a2928ada60)

**Comment by Septicity** [comment]
xapp-status-plugin, which holds the nm-applet and mint-update icons by default, now sizes icons separately for some reason; right click on the margin of the applet and you'll find the icon size settings there. Hopefully they attempt to sync the size with the theme and/or make the sizing available in the Panel Preferences menu soon.

**Comment by simphotonics** [comment]
Right clicking on the *margin* of the applet can be a bit fiddly, since one is more likely to click on an applet item or on the neighbouring panel item. For this reason I found it useful to temporarily move the applet to the right side of panel.

![xapp-status-plugin](https://github.com/user-attachments/assets/a11d7d0f-a989-469a-ae50-4e0d105580f7)

**Comment by bighugedev** [comment]
@Septicity @simphotonics 
Marvellous!
The jumped up Bluetooth icon (as shown [in the first post](https://github.com/linuxmint/xfce4-xapp-status-plugin/issues/10#issue-2452830770)) is fixed in a similar way. Although, right-clicking on the margin of the Bluetooth icon only helped to bring up the panel's context menu. From it, select the "panel parameters...", then go to the "Elements" tab and find the selected element shown on the screenshot. This element is in charge of the Bluetooth icon, double-click it to customise it, including defining its size.

<img width="526" height="652" alt="Image" src="https://github.com/user-attachments/assets/30b6d329-7c8a-40f8-bb05-d8c12e16374d" />

<img width="516" height="645" alt="Image" src="https://github.com/user-attachments/assets/1dcb3ada-0a54-476b-a738-4176ff759204" />

**Comment by bareego** [comment]
I found the easiest way is to right click on the panel, select Panel > Panel Preferences, click on the items tab and then at the bottom of the list are all the items of interest. Just select the one you want and click "Edit the current selected item".I still think there should be a global setting that all these different items follow, but I'm happy as I can adjust all the heights now, just have to go through each one and adjust it.
    On Sunday 25 January 2026 at 12:56:15 am AEST, bighugedev ***@***.***> wrote:  
 
 bighugedev left a comment (linuxmint/xfce4-xapp-status-plugin#10)
@Septicity @simphotonics
Marvellous!
The jumped up Bluetooth icon (as shown in the first post) is fixed in a similar way. Although, right-clicking on the margin of the Bluetooth icon only helped to bring up the panel's context menu. From it, select the "panel parameters...", then go to the "Elements" tab and find the selected element shown on the screenshot. This element is in charge of the Bluetooth icon, double-click it to customise it, including defining its size.
_2026-01-24_17-32-54.png (view on web)default.png (view on web)
