### ISSUE TITLE
When assigned to more than one panel, the status icons don't always show up in the same instance.

### ISSUE THREAD

**Issue by stoltzld** [linuxmint/xfce4-xapp-status-plugin#5]
![upper-Screenshot_2021-07-11_20-11-24](https://user-images.githubusercontent.com/5799151/125214290-508e5e00-e284-11eb-8ae6-441dacb9481b.png)
![lower-Screenshot_2021-07-11_20-10-53](https://user-images.githubusercontent.com/5799151/125214299-5be18980-e284-11eb-8b4e-850b3fea1d9a.png)
I have two of these, one assigned to my upper panel and one assigned to my lower panel.  Most of the time, my network status icons show up in my upper panel, but occasionally it shows up in the lower one.

**Comment by mtwebster** [comment]
Hi sorry for getting to this 'a bit' late - 

If these are both xapp status applets involved, they should both be showing the same content (not a particular icon in one, but not in the other).

I'm not sure what version you have of libxapp, but it's possible this has been fixed since 2.4.
ref:
linuxmint/xapp@8d0a712fba65e71b1bc0fd226c8b99af4b730ed8
linuxmint/xapp@33a0f45ead5c4f1d9ee27e8414fe0617d8b25536


If this is issue is still relevant, please let me know if you can still reproduce it under the current Mint version, or, if you're not using the latest, provide the versions of libxapp and xfce-xapp-status-applet you have.
